### ISSUE TITLE
PR checklist:

### ISSUE THREAD

**Issue by Osmosis-Wrench** [Osmosis-Wrench/OStrap#7]
Test working:

- [x] Import and export.
- [x] Compats load.
- [x] Compats purge.
- [x] Body mod swap.
- [x] Equip to player.
- [x] Equip to NPC.
- [x] OCum player.
- [x] OCum NPC.
- [x] Unequip from player.
- [x] Unequip from NPC.

**Comment by Osmosis-Wrench** [comment]
good for release
